<div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="<?php echo $this->url('admin-event'); ?>">Events</a>
        </li>
        <li class="breadcrumb-item">
            <?php echo $event->getName(); ?>
        </li>
        <li class="breadcrumb-item active">Task</li>
    </ol>
    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ')
        ->setMessageSeparatorString('')
        ->setMessageCloseString('</div>');

    echo $flash->render('error', ['alert', 'alert-dismissible', 'alert-danger']);
    echo $flash->render('info', ['alert', 'alert-dismissible', 'alert-info']);
    echo $flash->render('default', ['alert', 'alert-dismissible', 'alert-warning']);
    echo $flash->render('success', ['alert', 'alert-dismissible', 'alert-success']);
     ?>
    <form id="attendanceFrm" method="post" action="<?php echo $this->url('admin-event', ['action' => 'task-points',]); ?>">
        <input name="event_id" type="hidden" id="event_id" value="<?php echo $event->getId(); ?>">
        <div class="row">
            <div class="col">
                <input name="email" type="text" class="form-control" id="email" placeholder="Email">
            </div>
            <div class="col">
                <select name="task_id" class="form-control" id="task_id">
                    <?php foreach ($tasks as $task): ?>
                    <option value="<?php echo $task->getId(); ?>">
                        <?php echo $task->getTask(); ?>
                        (
                        <?php echo $task->getPoints() == 1 ? $task->getPoints() . " point" : $task->getPoints() . " points"; ?>)
                    </option>>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>
    <br>
    <div id="loadingMessage">🎥 Unable to access video stream (please make sure you have a webcam enabled)</div>
    <canvas id="canvas" hidden></canvas>
    <div id="output" hidden>
        <div id="outputMessage">No QR code detected.</div>
        <div hidden><b>Data:</b> <span id="outputData"></span></div>
    </div>
    <script src="/vendor/jsQR.js"></script>
    <script>
    var video = document.createElement("video");
    var canvasElement = document.getElementById("canvas");
    var canvas = canvasElement.getContext("2d");
    var loadingMessage = document.getElementById("loadingMessage");
    var outputContainer = document.getElementById("output");
    var outputMessage = document.getElementById("outputMessage");
    var outputData = document.getElementById("outputData");

    function drawLine(begin, end, color) {
        canvas.beginPath();
        canvas.moveTo(begin.x, begin.y);
        canvas.lineTo(end.x, end.y);
        canvas.lineWidth = 4;
        canvas.strokeStyle = color;
        canvas.stroke();
    }

    // Use facingMode: environment to attemt to get the front camera on phones
    navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } }).then(function(stream) {
        video.srcObject = stream;
        video.setAttribute("playsinline", true); // required to tell iOS safari we don't want fullscreen
        video.play();
        requestAnimationFrame(tick);
    });

    function tick() {
        loadingMessage.innerText = "⌛ Loading video..."
        if (video.readyState === video.HAVE_ENOUGH_DATA) {
            loadingMessage.hidden = true;
            canvasElement.hidden = false;
            outputContainer.hidden = false;

            canvasElement.height = video.videoHeight;
            canvasElement.width = video.videoWidth;
            canvas.drawImage(video, 0, 0, canvasElement.width, canvasElement.height);
            var imageData = canvas.getImageData(0, 0, canvasElement.width, canvasElement.height);
            var code = jsQR(imageData.data, imageData.width, imageData.height, {
                inversionAttempts: "dontInvert",
            });
            if (code) {
                document.getElementById("email").value = code.data;
                drawLine(code.location.topLeftCorner, code.location.topRightCorner, "#FF3B58");
                drawLine(code.location.topRightCorner, code.location.bottomRightCorner, "#FF3B58");
                drawLine(code.location.bottomRightCorner, code.location.bottomLeftCorner, "#FF3B58");
                drawLine(code.location.bottomLeftCorner, code.location.topLeftCorner, "#FF3B58");
                outputMessage.hidden = true;
                outputData.parentElement.hidden = false;
                outputData.innerText = code.data;

                document.getElementById("attendanceFrm").submit();
            } else {
                outputMessage.hidden = false;
                outputData.parentElement.hidden = true;
            }
        }
        requestAnimationFrame(tick);
    }
    </script>
</div>
<!-- /.container-fluid -->