<div class="container space-top-md-2">
    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">About
        <small>GigaMike</small>
    </h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="<?php echo $this->url('home'); ?>">Home</a>
        </li>
        <li class="breadcrumb-item active">About</li>
    </ol>
    <!-- Intro Content -->
    <div class="row">
        <div class="col-lg-6">
            <div class="text-center"><img class="img-fluid rounded mb-4" src="/img/logo.jpg" alt="GigaMike.net logo"></div>
        </div>
        <div class="col-lg-6">
            <h2>About Our Team</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed voluptate nihil eum consectetur similique? Consectetur, quod, incidunt, harum nisi dolores delectus reprehenderit voluptatem perferendis dicta dolorem non blanditiis ex fugiat.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, magni, aperiam vitae illum voluptatum aut sequi impedit non velit ab ea pariatur sint quidem corporis eveniet. Odit, temporibus reprehenderit dolorum!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, consequuntur, modi mollitia corporis ipsa voluptate corrupti eum ratione ex ea praesentium quibusdam? Aut, in eum facere corrupti necessitatibus perspiciatis quis?</p>
        </div>
    </div>
    <!-- /.row -->
    <!-- Team Members -->
    <h2>Our Team</h2>
    <div class="row">
        <div class="col-lg-4 mb-4">
            <div class="card h-100 text-center">
                <img class="card-img-top" src="/img/team/mik-g.jpg" alt="">
                <div class="card-body">
                    <h4 class="card-title">Michael Gerard Galon, MIM</h4>
                    <h6 class="card-subtitle mb-2 text-muted">Full Stack Developer</h6>
                </div>
                <div class="card-footer">
                    <a href="mailto:gigamike@gigamike.net">gigamike@gigamike.net</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 mb-4">
            <div class="card h-100 text-center">
                <img class="card-img-top" src="/img/team/amah-b.jpg" alt="">
                <div class="card-body">
                    <h4 class="card-title">Amah Buenaventura, CPA, MBA, (CMA)</h4>
                    <h6 class="card-subtitle mb-2 text-muted">Business Developer</h6>
                </div>
                <div class="card-footer">
                    <a href="mailto:gigamike@gigamike.net">amah@gigamike.net</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <!-- Our Customers -->
    <h2>Our Customers</h2>
    <div class="row">
        <div class="col-lg-2 col-sm-4 mb-4">
            <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-lg-2 col-sm-4 mb-4">
            <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-lg-2 col-sm-4 mb-4">
            <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-lg-2 col-sm-4 mb-4">
            <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-lg-2 col-sm-4 mb-4">
            <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </div>
        <div class="col-lg-2 col-sm-4 mb-4">
            <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </div>
    </div>
    <!-- /.row -->
</div>