<div class="container space-top-md-2">
    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Sign Up
        <small>Registration</small>
    </h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="<?php echo $this->url('home'); ?>">Home</a>
        </li>
        <li class="breadcrumb-item active">Registration</li>
    </ol>
    <div class="row">
        <div class="col-lg-8 mb-4">
            <?php
      $flash = $this->flashMessenger();
      $flash->setMessageOpenFormat('<div%s role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
          ')
          ->setMessageSeparatorString('')
          ->setMessageCloseString('</div>');

      echo $flash->render('error', ['alert', 'alert-dismissible', 'alert-danger']);
      echo $flash->render('info', ['alert', 'alert-dismissible', 'alert-info']);
      echo $flash->render('default', ['alert', 'alert-dismissible', 'alert-warning']);
      echo $flash->render('success', ['alert', 'alert-dismissible', 'alert-success']);
       ?>
            <div class="card card-register mx-auto">
                <div class="card-body">
                    <a href="#" class="btn btn-block btn-social btn-facebook">
                        <i class="fab fa-facebook"></i> Sign up with Facebook
                    </a>
                    <a href="#" class="btn btn-block btn-social btn-google">
                        <i class="fab fa-google"></i> Sign up with Google
                    </a>
                </div>
            </div>
            <div class="text-center mt-4 mb-4">
                OR
            </div>
            <div class="card card-register mx-auto">
                <div class="card-header">Manual Registration</div>
                <div class="card-body">
                    <?php
          $form->setAttribute('action', $this->url('registration'));
          $form->setAttribute('id', 'registrationForm');
          $form->setAttribute('name', 'registration');
          $form->prepare();
          echo $this->form()->openTag($form);
          ?>
                    <input type="hidden" name="referral_id" value="<?php echo $this->referral_id; ?>">
                    <?= $this->formElement($form->get('security')) ?>
                    <div class="form-group">
                        <div class="form-group">
                            <div class="form-row">
                                <div class="col-md-12">
                                    <div class="form-label-group">
                                        <?= $this->formElement($form->get('email')) ?>
                                        <?= $this->formLabel($form->get('email')) ?>
                                        <?= $this->formElementErrors()->render($form->get('email'), ['class' => 'help-block']) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-label-group">
                                        <?= $this->formElement($form->get('password')) ?>
                                        <?= $this->formLabel($form->get('password')) ?>
                                        <?= $this->formElementErrors()->render($form->get('password'), ['class' => 'help-block']) ?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-label-group">
                                        <?= $this->formElement($form->get('confirm_password')) ?>
                                        <?= $this->formLabel($form->get('confirm_password')) ?>
                                        <?= $this->formElementErrors()->render($form->get('confirm_password'), ['class' => 'help-block']) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-4">
                                <div class="form-label-group">
                                    <?= $this->formElement($form->get('first_name')) ?>
                                    <?= $this->formLabel($form->get('first_name')) ?>
                                    <?= $this->formElementErrors()->render($form->get('first_name'), ['class' => 'help-block']) ?>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-label-group">
                                    <?= $this->formElement($form->get('middle_name')) ?>
                                    <?= $this->formLabel($form->get('middle_name')) ?>
                                    <?= $this->formElementErrors()->render($form->get('middle_name'), ['class' => 'help-block']) ?>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-label-group">
                                    <?= $this->formElement($form->get('last_name')) ?>
                                    <?= $this->formLabel($form->get('last_name')) ?>
                                    <?= $this->formElementErrors()->render($form->get('last_name'), ['class' => 'help-block']) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <?= $this->formElement($form->get('title')) ?>
                                    <?= $this->formLabel($form->get('title')) ?>
                                    <?= $this->formElementErrors()->render($form->get('title'), ['class' => 'help-block']) ?>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <?= $this->formElement($form->get('gender')) ?>
                                    <?= $this->formLabel($form->get('gender')) ?>
                                    <?= $this->formElementErrors()->render($form->get('gender'), ['class' => 'help-block']) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <?= $this->formElement($form->get('city')) ?>
                                    <?= $this->formLabel($form->get('city')) ?>
                                    <?= $this->formElementErrors()->render($form->get('city'), ['class' => 'help-block']) ?>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <?= $this->formElement($form->get('country_id')) ?>
                                    <?= $this->formLabel($form->get('country_id')) ?>
                                    <?= $this->formElementErrors()->render($form->get('country_id'), ['class' => 'help-block']) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <?= $this->formElement($form->get('mobile_no')) ?>
                                    <?= $this->formLabel($form->get('mobile_no')) ?>
                                    <?= $this->formElementErrors()->render($form->get('mobile_no'), ['class' => 'help-block']) ?>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <?= $this->formElement($form->get('birth_date')) ?>
                                    <?= $this->formLabel($form->get('birth_date')) ?>
                                    <?= $this->formElementErrors()->render($form->get('birth_date'), ['class' => 'help-block']) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <?= $this->formLabel($form->get('photo')) ?>
                                    <?= $this->formFile($form->get('photo')) ?>
                                    <?= $this->formElementErrors()->render($form->get('photo'), ['class' => 'help-block']) ?>
                                </div>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-label-group">
                                    <?= $this->formElement($form->get('captcha')) ?>
                                    <?= $this->formLabel($form->get('captcha')) ?>
                                    <?= $this->formElementErrors()->render($form->get('captcha'), ['class' => 'help-block']) ?>
                                </div>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                    <?php echo $this->form()->closeTag();?>
                    <div class="text-center">
                        <a class="d-block small mt-3" href="<?php echo $this->url('login'); ?>">Login Page</a>
                        <a class="d-block small" href="<?php echo $this->url('forgot-password'); ?>">Forgot Password?</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 mb-4">
            <h3>Signup</h3>
            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            </p>
        </div>
    </div>
    <script>
    $(document).ready(function() {
        $("#birth_date").datepicker({
            dateFormat: "yy-mm-dd",
            changeMonth: true,
            changeYear: true,
            yearRange: "-100:+0",
        });
    });
    </script>
</div>