<div class="container space-top-md-2">
    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Welcome
        <small>
            <?php echo $this->user->getFirstName(); ?>
            <?php echo $this->user->getLastName(); ?></small>
    </h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="<?php echo $this->url('member'); ?>">Home</a>
        </li>
        <li class="breadcrumb-item active">Dashboard</li>
    </ol>
    <!-- Content Row -->
    <div class="row">
        <!-- Sidebar Column -->
        <div class="col-lg-3 mb-4">
            <?php echo $this->partial('partial/member/menu.phtml', [
                'route' => $this->route,
                'action' => $this->action,
            ]); ?>
        </div>
        <!-- Content Column -->
        <div class="col-lg-9 mb-4">
            <?php
      $flash = $this->flashMessenger();
      $flash->setMessageOpenFormat('<div%s role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
          ')
          ->setMessageSeparatorString('')
          ->setMessageCloseString('</div>');

      echo $flash->render('error', ['alert', 'alert-dismissible', 'alert-danger']);
      echo $flash->render('info', ['alert', 'alert-dismissible', 'alert-info']);
      echo $flash->render('default', ['alert', 'alert-dismissible', 'alert-warning']);
      echo $flash->render('success', ['alert', 'alert-dismissible', 'alert-success']);
       ?>
            <div class="card card-register mx-auto">
                <div class="card-header">Dashboard</div>
                <div class="card-body">
                    <h2>My Events</h2>
                    <table class="table table-bordered table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Event</th>
                                <th>Date Register</th>
                                <th>Check-in</th>
                                <th>My Certificate</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (count($this->paginator)): ?>
                            <?php foreach ($this->paginator as $event): ?>
                            <tr>
                                <td>
                                    <a href="<?php echo $this->url('events', ['action' => 'join', 'id' => $event->event_id,]); ?>">
                                        <?php echo $this->escapeHtml($event->name); ?></a>
                                </td>
                                <td>
                                    <?php echo $this->escapeHtml(date('M d, Y H:i:s', strtotime($event->created_datetime))); ?>
                                </td>
                                <td>
                                    <?php if (!empty($event->attend_datetime)): ?>
                                    <?php echo $this->escapeHtml(date('M d, Y H:i:s', strtotime($event->attend_datetime))); ?>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <?php if (!empty($event->attend_datetime)): ?>
                                    <a href="<?php echo $this->url('member', ['action' => 'pdf', 'id' => $event->event_id,]); ?>">Download</a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </div>
</div>
<!-- /.row -->
</div>